## catalog of libraries and plugins used to build and run the RyzomConverter project

[versions]

jme = "3.9.0-stable"

[libraries]

commons-io = "commons-io:commons-io:2.21.0"
javax-annotation = "org.realityforge.javax.annotation:javax.annotation:1.1.1"

jme3-core = { module = "org.jmonkeyengine:jme3-core", version.ref = "jme" }
jme3-desktop = { module = "org.jmonkeyengine:jme3-desktop", version.ref = "jme" }
jme3-jogg = { module = "org.jmonkeyengine:jme3-jogg", version.ref = "jme" }
jme3-plugins = { module = "org.jmonkeyengine:jme3-plugins", version.ref = "jme" }

[bundles]

[plugins]
